
import { Recipe, Gift } from './types';

export const INITIAL_RECIPES: Recipe[] = [
  {
    id: '1',
    title: 'Bowl Detox de Quinoa Real',
    description: 'La combinación perfecta de superalimentos para resetear tu metabolismo.',
    category: 'Almuerzo',
    time: '15 min',
    timeValue: 15,
    calories: 320,
    ingredients: ['Quinoa orgánica', 'Aguacate Haas', 'Kale premium', 'Semillas de cáñamo'],
    instructions: ['Lavar la quinoa.', 'Mezclar con vegetales frescos.', 'Aderezar con limón real.'],
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=800&auto=format&fit=crop',
    difficulty: 'Fácil',
    dietaryRestrictions: ['Vegano', 'Sin Gluten'],
    rating: 4.9,
    reviews: 1240
  },
  {
    id: '2',
    title: 'Salmón Salvaje al Eneldo',
    description: 'Proteína de alta calidad para una quema de grasa eficiente.',
    category: 'Cena',
    time: '20 min',
    timeValue: 20,
    calories: 410,
    ingredients: ['Filete de salmón salvaje', 'Espárragos trigueros', 'Aceite de oliva virgen extra'],
    instructions: ['Sellar el salmón.', 'Hornear con vegetales.', 'Servir inmediatamente.'],
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?q=80&w=800&auto=format&fit=crop',
    difficulty: 'Media',
    dietaryRestrictions: ['Sin Gluten', 'Paleo'],
    rating: 5.0,
    reviews: 890
  },
  {
    id: '3',
    title: 'Panqueques de Avena y Chía',
    description: 'Desayuno energético sin harinas refinadas.',
    category: 'Desayuno',
    time: '10 min',
    timeValue: 10,
    calories: 250,
    ingredients: ['Avena integral', 'Huevo orgánico', 'Semillas de chía', 'Canela'],
    instructions: ['Licuar ingredientes.', 'Cocinar en sartén antiadherente.', 'Decorar con frutos rojos.'],
    image: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?q=80&w=800&auto=format&fit=crop',
    difficulty: 'Fácil',
    dietaryRestrictions: ['Vegetariano'],
    rating: 4.8,
    reviews: 560
  },
  {
    id: '4',
    title: 'Tacos de Lechuga con Atún',
    description: 'Snack ultra bajo en carbohidratos para definición.',
    category: 'Snack',
    time: '5 min',
    timeValue: 5,
    calories: 180,
    ingredients: ['Hojas de lechuga romana', 'Atún en agua', 'Pico de gallo', 'Limón'],
    instructions: ['Drenar el atún.', 'Colocar en las hojas de lechuga.', 'Añadir pico de gallo.'],
    image: 'https://images.unsplash.com/photo-1512852939750-1305098529bf?q=80&w=800&auto=format&fit=crop',
    difficulty: 'Fácil',
    dietaryRestrictions: ['Paleo', 'Keto'],
    rating: 4.7,
    reviews: 320
  },
  {
    id: '5',
    title: 'Smoothie Verde Quema Grasa',
    description: 'El elixir matutino para despertar el metabolismo.',
    category: 'Desayuno',
    time: '3 min',
    timeValue: 3,
    calories: 150,
    ingredients: ['Espinaca', 'Manzana verde', 'Jengibre fresco', 'Agua de coco'],
    instructions: ['Lavar todo.', 'Licuar a alta potencia.', 'Beber en ayunas.'],
    image: 'https://images.unsplash.com/photo-1610970881699-44a5587cabec?q=80&w=800&auto=format&fit=crop',
    difficulty: 'Fácil',
    dietaryRestrictions: ['Vegano', 'Sin Gluten'],
    rating: 4.9,
    reviews: 2100
  },
  {
    id: '6',
    title: 'Pollo al Limón y Romero',
    description: 'Un clásico saludable con un toque mediterráneo.',
    category: 'Almuerzo',
    time: '25 min',
    timeValue: 25,
    calories: 380,
    ingredients: ['Pechuga de pollo', 'Limón amarillo', 'Romero fresco', 'Ajo'],
    instructions: ['Marinar el pollo.', 'Cocinar a la plancha.', 'Servir con ensalada verde.'],
    image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?q=80&w=800&auto=format&fit=crop',
    difficulty: 'Media',
    dietaryRestrictions: ['Keto', 'Sin Gluten'],
    rating: 4.8,
    reviews: 740
  },
  {
    id: '7',
    title: 'Pudín de Chía y Coco',
    description: 'Postre saciante y rico en Omega-3.',
    category: 'Postre',
    time: '5 min',
    timeValue: 5,
    calories: 210,
    ingredients: ['Semillas de chía', 'Leche de coco', 'Vainilla', 'Stevia'],
    instructions: ['Mezclar ingredientes.', 'Reposar 4 horas.', 'Servir frío.'],
    image: 'https://images.unsplash.com/photo-1534353436294-0dbd4bdac845?q=80&w=800&auto=format&fit=crop',
    difficulty: 'Fácil',
    dietaryRestrictions: ['Vegano', 'Keto'],
    rating: 4.6,
    reviews: 430
  },
  {
    id: '8',
    title: 'Ensalada de Garbanzos y Feta',
    description: 'Proteína vegetal de alta densidad nutricional.',
    category: 'Almuerzo',
    time: '12 min',
    timeValue: 12,
    calories: 290,
    ingredients: ['Garbanzos cocidos', 'Queso feta', 'Pepino', 'Tomatitos'],
    instructions: ['Picar los vegetales.', 'Mezclar con garbanzos.', 'Aliñar con aceite de oliva.'],
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=800&auto=format&fit=crop',
    difficulty: 'Fácil',
    dietaryRestrictions: ['Vegetariano'],
    rating: 4.7,
    reviews: 615
  },
  {
    id: '9',
    title: 'Chips de Camote al Horno',
    description: 'Alternativa saludable a las papas fritas.',
    category: 'Snack',
    time: '30 min',
    timeValue: 30,
    calories: 120,
    ingredients: ['Camote', 'Paprika', 'Sal marina', 'Aceite de coco'],
    instructions: ['Cortar en láminas finas.', 'Condimentar.', 'Hornear hasta que estén crujientes.'],
    image: 'https://images.unsplash.com/photo-1528751014839-b73414c773ff?q=80&w=800&auto=format&fit=crop',
    difficulty: 'Media',
    dietaryRestrictions: ['Vegano', 'Sin Gluten'],
    rating: 4.5,
    reviews: 290
  },
  {
    id: '10',
    title: 'Ceviche de Champiñones',
    description: 'Versión ligera y fresca del ceviche tradicional.',
    category: 'Cena',
    time: '15 min',
    timeValue: 15,
    calories: 140,
    ingredients: ['Champiñones frescos', 'Cebolla morada', 'Cilantro', 'Mucho limón'],
    instructions: ['Laminar champiñones.', 'Mezclar con el jugo de limón.', 'Dejar marinar 10 min.'],
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
    difficulty: 'Fácil',
    dietaryRestrictions: ['Vegano', 'Sin Gluten'],
    rating: 4.9,
    reviews: 580
  },
  {
    id: '11',
    title: 'Huevos Nube con Espinacas',
    description: 'Desayuno gourmet rico en proteínas.',
    category: 'Desayuno',
    time: '15 min',
    timeValue: 15,
    calories: 220,
    ingredients: ['Claras de huevo', 'Yema central', 'Espinaca baby', 'Pimienta'],
    instructions: ['Batir claras a punto nieve.', 'Hornear y colocar la yema.', 'Servir sobre espinacas.'],
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?q=80&w=800&auto=format&fit=crop',
    difficulty: 'Avanzada',
    dietaryRestrictions: ['Vegetariano', 'Keto'],
    rating: 4.8,
    reviews: 190
  },
  {
    id: '12',
    title: 'Tarta de Manzana Fit',
    description: 'Sin harinas y baja en azúcar.',
    category: 'Postre',
    time: '45 min',
    timeValue: 45,
    calories: 190,
    ingredients: ['Manzana', 'Claras de huevo', 'Yogur griego', 'Canela'],
    instructions: ['Mezclar yogur y claras.', 'Verter sobre manzanas.', 'Hornear hasta dorar.'],
    image: 'https://images.unsplash.com/photo-1568571780765-9276ac8b75a2?q=80&w=800&auto=format&fit=crop',
    difficulty: 'Media',
    dietaryRestrictions: ['Vegetariano'],
    rating: 4.7,
    reviews: 410
  }
];

export const PREMIUM_GIFTS: Gift[] = [
  { 
    id: 'g1', 
    title: 'Biblia del Ayuno 16:8', 
    description: 'La estrategia secreta para resetear tu insulina y quemar grasa mientras duermes.', 
    longDescription: 'Este no es un libro común. Es el protocolo exacto utilizado por atletas de élite para mantener niveles de grasa por debajo del 10% sin sacrificar músculo. Incluye ventanas de alimentación personalizadas.',
    icon: 'fa-bolt-lightning', 
    type: 'PDF', 
    value: '$47',
    tag: 'MÁS POPULAR'
  },
  { 
    id: 'g2', 
    title: 'App Móvil VidaSana VIP', 
    description: 'Lleva tu nutricionista y chef AI en el bolsillo a donde vayas.', 
    longDescription: 'Acceso exclusivo a nuestra Progressive Web App. Sincronización en tiempo real, escáner de alimentos y generador de listas de compras inteligente.',
    icon: 'fa-mobile-vibration', 
    type: 'Software', 
    value: '$97',
    tag: 'INSTALACIÓN INSTANTÁNEA'
  },
  { 
    id: 'g3', 
    title: 'Protocolo Anti-Inflamatorio', 
    description: 'Elimina la hinchazón y recupera tu energía vital en solo 72 horas.', 
    longDescription: 'La inflamación es el asesino silencioso. Este protocolo utiliza biohacking nutricional para desinflamar tus órganos y aclarar tu mente.',
    icon: 'fa-droplet-slash', 
    type: 'Guía', 
    value: '$67',
    tag: 'EFECTO RÁPIDO'
  },
  { 
    id: 'g4', 
    title: 'Comunidad Elite 24/7', 
    description: 'Nunca estarás solo. Soporte directo con expertos y círculo de triunfadores.', 
    longDescription: 'Acceso al grupo privado donde compartimos recetas secretas, resultados en tiempo real y mentorías semanales en vivo.',
    icon: 'fa-crown', 
    type: 'Video', 
    value: '$197',
    tag: 'ACCESO ILIMITADO'
  },
  { 
    id: 'g5', 
    title: 'Masterclass: Adiós Azúcar', 
    description: 'Hackea tu cerebro para eliminar los antojos de dulce para siempre.', 
    longDescription: 'Descubre la ciencia de la dopamina y cómo reconfigurar tus receptores de sabor para disfrutar de la comida real sin depender de químicos.',
    icon: 'fa-brain', 
    type: 'Video', 
    value: '$59',
    tag: 'CIENCIA PURA'
  },
  { 
    id: 'g6', 
    title: 'Recetario Express 5 min', 
    description: 'Comidas gourmet para gente sin tiempo. Máximo sabor en minutos.', 
    longDescription: '50 recetas que puedes preparar en menos tiempo del que tardas en pedir comida rápida. Saludable, rico y ultra veloz.',
    icon: 'fa-stopwatch', 
    type: 'PDF', 
    value: '$37',
    tag: 'ULTRA RÁPIDO'
  }
];

export const CATEGORIES = ['Desayuno', 'Almuerzo', 'Cena', 'Snack', 'Postre'];
export const RESTRICTIONS = ['Vegano', 'Vegetariano', 'Sin Gluten', 'Sin Lactosa'];
